'use client';
/* eslint-disable @next/next/no-img-element -- Posters are authenticated, same-origin files generated by this LAN server. */
/* eslint-disable @next/next/no-location-assign-relative-destination -- Vinext's Next navigation shims currently duplicate React context in this client runtime. */

import { FormEvent, useEffect, useMemo, useState } from 'react';
import type { PlaybackProgress, PublicMediaItem } from '@/server/types';

interface LibraryResponse {
  items: PublicMediaItem[];
  progress: Record<string, PlaybackProgress>;
}

interface ServerInfo {
  secure: boolean;
  encoder: string;
  mediaCount: number;
  libraryCount: number;
  lanUrls: string[];
  publicUrl?: string;
  canPickLocalFolder: boolean;
  nativeFolderPicker: boolean;
  canManageCloud: boolean;
  cloudSourceCount: number;
}

interface CloudSourceSummary {
  id: string;
  provider: 'quark' | 'baidu';
  name: string;
  connection: 'OpenList WebDAV' | '百度官方 API';
  rootPath: string;
  endpoint?: string;
  fileCount: number;
  lastScanAt?: string;
  error?: string;
}

interface BaiduAuthorization {
  sessionId: string;
  userCode: string;
  verificationUrl: string;
  qrCodeDataUrl: string;
  expiresAt: string;
  intervalSeconds: number;
}

interface CloudConnectorCapabilities {
  baidu: {
    available: boolean;
    login: 'qr';
    appFolder: string;
    activeAuthorization?: BaiduAuthorization;
    unavailableReason?: string;
  };
  quark: {
    available: false;
    login: 'official-api-required';
    advancedWebDavAvailable: true;
    unavailableReason: string;
  };
}

const posterTones = ['violet', 'ocean', 'ember', 'mint', 'gold', 'rose'];
const pairingMessages: Record<string, string> = {
  invalid_pairing_code: '配对码不正确，请查看电脑端本次启动显示的六位数字。',
  too_many_attempts: '尝试次数过多，请等待五分钟后再试。',
  origin_required: '浏览器安全校验失败，请从 Localis 页面重新配对。',
};

function formatDuration(seconds: number) {
  if (!Number.isFinite(seconds) || seconds <= 0) return '—';
  const total = Math.floor(seconds);
  const hours = Math.floor(total / 3600);
  const minutes = Math.floor((total % 3600) / 60);
  const remainder = total % 60;
  return hours > 0
    ? `${hours}:${String(minutes).padStart(2, '0')}:${String(remainder).padStart(2, '0')}`
    : `${minutes}:${String(remainder).padStart(2, '0')}`;
}

function mediaLabel(item: PublicMediaItem) {
  const resolution = item.width && item.height ? `${item.width}×${item.height}` : item.kind === 'audio' ? '音频' : '视频';
  if (item.projection === 'equirect180') return `VR180 · ${item.stereo.toUpperCase()} · ${resolution}`;
  if (item.projection === 'equirect360') return `360° · ${item.stereo.toUpperCase()} · ${resolution}`;
  return `${resolution} · ${(item.videoCodec || item.audioCodec || item.extension.slice(1)).toUpperCase()}`;
}

async function jsonFetch<T>(url: string, init?: RequestInit): Promise<T> {
  const response = await fetch(url, {
    credentials: 'include',
    ...init,
    headers: { 'Content-Type': 'application/json', ...init?.headers },
  });
  const body = await response.json().catch(() => ({})) as Record<string, unknown>;
  if (!response.ok) throw Object.assign(new Error(String(body.message || body.error || `HTTP ${response.status}`)), { status: response.status });
  return body as T;
}

export function MediaLibraryView() {
  const [items, setItems] = useState<PublicMediaItem[]>([]);
  const [progress, setProgress] = useState<Record<string, PlaybackProgress>>({});
  const [server, setServer] = useState<ServerInfo>();
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState<'all' | 'recent' | 'video' | 'audio'>('all');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [needsPairing, setNeedsPairing] = useState(false);
  const [pairCode, setPairCode] = useState('');
  const [pairError, setPairError] = useState('');
  const [folderOpen, setFolderOpen] = useState(false);
  const [folderPath, setFolderPath] = useState('');
  const [folderBusy, setFolderBusy] = useState(false);
  const [folderError, setFolderError] = useState('');
  const [cloudOpen, setCloudOpen] = useState(false);
  const [cloudProvider, setCloudProvider] = useState<'quark' | 'baidu'>('baidu');
  const [cloudSources, setCloudSources] = useState<CloudSourceSummary[]>([]);
  const [cloudConnectors, setCloudConnectors] = useState<CloudConnectorCapabilities>();
  const [cloudBusy, setCloudBusy] = useState(false);
  const [cloudError, setCloudError] = useState('');
  const [webDav, setWebDav] = useState({ baseUrl: 'http://127.0.0.1:5244/dav/', rootPath: '/Quark', username: 'localis-reader', password: '' });
  const [baiduAuthorization, setBaiduAuthorization] = useState<BaiduAuthorization>();

  const loadLibrary = async () => {
    setLoading(true);
    setError('');
    try {
      const status = await jsonFetch<{ paired: boolean }>('/api/pair/status');
      if (!status.paired) {
        setNeedsPairing(true);
        return;
      }
      const [library, serverInfo] = await Promise.all([
        jsonFetch<LibraryResponse>('/api/library'),
        jsonFetch<ServerInfo>('/api/server'),
      ]);
      setItems(library.items);
      setProgress(library.progress);
      setServer(serverInfo);
      setNeedsPairing(false);
    } catch (cause) {
      const status = (cause as { status?: number }).status;
      if (status === 401) setNeedsPairing(true);
      else setError(cause instanceof Error ? cause.message : '无法连接 Localis 服务');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    const timer = window.setTimeout(() => void loadLibrary(), 0);
    return () => window.clearTimeout(timer);
  }, []);
  useEffect(() => {
    const shortcut = (event: KeyboardEvent) => {
      if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') {
        event.preventDefault();
        document.querySelector<HTMLInputElement>('#media-search')?.focus();
      }
    };
    window.addEventListener('keydown', shortcut);
    return () => window.removeEventListener('keydown', shortcut);
  }, []);

  const filtered = useMemo(() => items.filter((item) => {
    if (filter === 'video' && item.kind !== 'video') return false;
    if (filter === 'audio' && item.kind !== 'audio') return false;
    if (filter === 'recent' && !progress[item.id]?.position) return false;
    return `${item.title} ${item.fileName} ${item.relativePath}`.toLowerCase().includes(query.trim().toLowerCase());
  }), [items, progress, query, filter]);
  const featured = items.find((item) => item.kind === 'video' && progress[item.id]?.position > 0)
    || items.find((item) => item.kind === 'video')
    || items[0];
  const featuredProgress = featured ? progress[featured.id] : undefined;
  const featuredPercent = featuredProgress?.duration
    ? Math.min(100, (featuredProgress.position / featuredProgress.duration) * 100)
    : 0;

  const pair = async (event: FormEvent) => {
    event.preventDefault();
    setPairError('');
    try {
      await jsonFetch('/api/pair/verify', { method: 'POST', body: JSON.stringify({ code: pairCode }) });
      setPairCode('');
      await loadLibrary();
    } catch (cause) {
      const message = cause instanceof Error ? cause.message : '';
      setPairError(pairingMessages[message] || message || '配对失败');
    }
  };

  const addFolder = async (event: FormEvent) => {
    event.preventDefault();
    if (!folderPath.trim()) return;
    try {
      await jsonFetch('/api/library/folders', { method: 'POST', body: JSON.stringify({ path: folderPath }) });
      setFolderPath('');
      setFolderOpen(false);
      await loadLibrary();
    } catch (cause) {
      setFolderError(cause instanceof Error ? cause.message : '添加文件夹失败');
    }
  };

  const pickFolder = async () => {
    setFolderBusy(true);
    setFolderError('');
    try {
      const result = await jsonFetch<{ cancelled: boolean; selected?: string }>('/api/library/folders/pick', { method: 'POST', body: '{}' });
      if (!result.cancelled) {
        setFolderPath('');
        setFolderOpen(false);
        await loadLibrary();
      }
    } catch (cause) {
      setFolderError(cause instanceof Error ? cause.message : '无法打开文件夹选择器');
    } finally {
      setFolderBusy(false);
    }
  };

  const refreshLibrary = async () => {
    setLoading(true);
    setError('');
    try {
      await jsonFetch('/api/library/refresh', { method: 'POST', body: '{}' });
      await loadLibrary();
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : '刷新媒体库失败');
      setLoading(false);
    }
  };

  const loadCloudSources = async () => {
    try {
      const result = await jsonFetch<{ sources: CloudSourceSummary[] }>('/api/cloud/sources');
      setCloudSources(result.sources);
    } catch (cause) {
      setCloudError(cause instanceof Error ? cause.message : '无法读取云盘连接');
    }
  };

  const loadCloudConnectors = async () => {
    try {
      const result = await jsonFetch<CloudConnectorCapabilities>('/api/cloud/connectors');
      setCloudConnectors(result);
      if (result.baidu.activeAuthorization) setBaiduAuthorization(result.baidu.activeAuthorization);
    } catch (cause) {
      setCloudError(cause instanceof Error ? cause.message : '无法读取云盘登录能力');
    }
  };

  const openCloudManager = () => {
    setCloudError('');
    setCloudOpen(true);
    void Promise.all([loadCloudSources(), loadCloudConnectors()]);
  };

  const connectWebDav = async (event: FormEvent) => {
    event.preventDefault();
    setCloudBusy(true);
    setCloudError('');
    try {
      await jsonFetch('/api/cloud/webdav', {
        method: 'POST',
        body: JSON.stringify({
          provider: cloudProvider,
          name: cloudProvider === 'quark' ? '夸克网盘' : '百度网盘 · OpenList',
          ...webDav,
        }),
      });
      setWebDav((current) => ({ ...current, password: '' }));
      await Promise.all([loadCloudSources(), loadLibrary()]);
    } catch (cause) {
      setCloudError(cause instanceof Error ? cause.message : '连接 OpenList 失败');
    } finally {
      setCloudBusy(false);
    }
  };

  const startBaiduAuthorization = async (event: FormEvent) => {
    event.preventDefault();
    setCloudBusy(true);
    setCloudError('');
    try {
      const authorization = await jsonFetch<BaiduAuthorization>('/api/cloud/baidu/device', {
        method: 'POST',
        body: JSON.stringify({ name: '百度网盘' }),
      });
      setBaiduAuthorization(authorization);
    } catch (cause) {
      setCloudError(cause instanceof Error ? cause.message : '无法开始百度授权');
    } finally {
      setCloudBusy(false);
    }
  };

  useEffect(() => {
    if (!baiduAuthorization) return;
    let cancelled = false;
    let timer: number | undefined;
    let transientFailures = 0;
    const schedule = (seconds: number) => {
      if (timer !== undefined) window.clearTimeout(timer);
      timer = window.setTimeout(() => { if (!cancelled) void poll(); }, Math.max(1, seconds) * 1000);
    };
    const poll = async () => {
      try {
        const result = await jsonFetch<{ state: 'pending' | 'authorized'; retryAfterSeconds?: number }>(`/api/cloud/baidu/device/${baiduAuthorization.sessionId}`);
        if (cancelled) return;
        transientFailures = 0;
        if (result.state === 'authorized') {
          setBaiduAuthorization(undefined);
          await Promise.all([loadCloudSources(), loadCloudConnectors(), loadLibrary()]);
          return;
        }
        schedule(Math.max(5, result.retryAfterSeconds || baiduAuthorization.intervalSeconds));
      } catch (cause) {
        if (cancelled) return;
        const status = (cause as { status?: number }).status;
        const message = cause instanceof Error ? cause.message : '百度授权轮询失败';
        if (status === 403 || status === 404 || status === 410) {
          setBaiduAuthorization(undefined);
          setCloudError(message);
          return;
        }
        transientFailures += 1;
        setCloudError(`${message}；网络恢复后会自动重试。`);
        schedule(Math.min(30, 5 * 2 ** Math.min(3, transientFailures - 1)));
      }
    };
    schedule(baiduAuthorization.intervalSeconds);
    return () => {
      cancelled = true;
      if (timer !== undefined) window.clearTimeout(timer);
    };
  }, [baiduAuthorization]);

  const cancelBaiduLink = async () => {
    const authorization = baiduAuthorization;
    if (!authorization) return;
    setBaiduAuthorization(undefined);
    setCloudError('');
    try {
      await jsonFetch(`/api/cloud/baidu/device/${authorization.sessionId}`, { method: 'DELETE' });
    } catch (cause) {
      if ((cause as { status?: number }).status !== 404) setCloudError(cause instanceof Error ? cause.message : '无法取消百度授权');
    }
  };

  const removeCloudSource = async (id: string) => {
    setCloudBusy(true);
    setCloudError('');
    try {
      await jsonFetch(`/api/cloud/sources/${id}`, { method: 'DELETE' });
      await Promise.all([loadCloudSources(), loadLibrary()]);
    } catch (cause) {
      setCloudError(cause instanceof Error ? cause.message : '移除云盘失败');
    } finally {
      setCloudBusy(false);
    }
  };

  const refreshCloudSources = async () => {
    setCloudBusy(true);
    setCloudError('');
    try {
      await jsonFetch('/api/cloud/refresh', { method: 'POST', body: '{}' });
      await Promise.all([loadCloudSources(), loadLibrary()]);
    } catch (cause) {
      setCloudError(cause instanceof Error ? cause.message : '刷新云盘失败');
    } finally {
      setCloudBusy(false);
    }
  };

  if (needsPairing) {
    return (
      <main className="pairing-page">
        <section className="pairing-panel">
          <span className="brand-mark large"><i /></span>
          <p className="eyebrow">PRIVATE LAN CONNECTION</p>
          <h1>连接你的私人媒体库</h1>
          <p>在电脑端 Localis 窗口中找到六位配对码。视频始终通过当前局域网传输。</p>
          <form onSubmit={pair}>
            <input aria-label="六位配对码" autoFocus autoComplete="one-time-code" inputMode="numeric" maxLength={6} pattern="[0-9]{6}" placeholder="000000" value={pairCode} onChange={(event) => setPairCode(event.target.value.replace(/\D/g, ''))} />
            <button disabled={pairCode.length !== 6}>安全连接</button>
          </form>
          {pairError && <div className="inline-error" role="alert">{pairError}</div>}
          <small>Vision Pro 端无需安装 App、证书或描述文件</small>
        </section>
      </main>
    );
  }

  return (
    <main className="app-shell">
      <aside className="sidebar">
        <a className="brand" href="#" aria-label="Localis 首页"><span className="brand-mark"><i /></span><span>Localis</span></a>
        <nav aria-label="媒体导航">
          <button className={`nav-item ${filter === 'all' ? 'active' : ''}`} onClick={() => setFilter('all')}><span>⌂</span>媒体库</button>
          <button className={`nav-item ${filter === 'recent' ? 'active' : ''}`} onClick={() => setFilter('recent')}><span>◷</span>最近播放</button>
          <button className={`nav-item ${filter === 'video' ? 'active' : ''}`} onClick={() => setFilter('video')}><span>▣</span>视频</button>
          <button className={`nav-item ${filter === 'audio' ? 'active' : ''}`} onClick={() => setFilter('audio')}><span>♫</span>音频</button>
        </nav>
        <div className="sidebar-spacer" />
        <div className="server-card">
          <div className="server-line"><span className="status-dot" />局域网服务在线</div>
          <strong>{server?.publicUrl || server?.lanUrls[0]?.replace(/^https?:\/\//, '') || '正在检测…'}</strong>
          <small>{server?.secure ? '可信 HTTPS · WebXR 可用' : 'HTTP · 仅桌面测试 WebXR'}</small>
        </div>
        <button className="nav-item" onClick={() => void refreshLibrary()}><span>↻</span>刷新媒体库</button>
      </aside>

      <section className="content" id="library">
        <header className="topbar">
          <label className="search"><span>⌕</span><input id="media-search" aria-label="搜索媒体" placeholder="搜索影片、音乐或文件夹" value={query} onChange={(event) => setQuery(event.target.value)} /><kbd>⌘ K</kbd></label>
          <button className="pair-button"><span className="status-dot" />当前设备已配对</button>
          <button className="avatar" aria-label="Localis 服务状态">L</button>
        </header>

        {server && !server.secure && typeof window !== 'undefined' && !['localhost', '127.0.0.1'].includes(window.location.hostname) && (
          <div className="security-banner"><strong>普通播放可用</strong><span>当前地址不是可信 HTTPS，浏览器会禁用 WebXR。请使用 Localis 提供的可信域名。</span></div>
        )}
        {error && <div className="inline-error library-error" role="alert">{error}<button onClick={() => setError('')}>关闭</button></div>}

        <div className="page-heading">
          <div><p className="eyebrow">YOUR PRIVATE CINEMA</p><h1>晚上好，继续探索。</h1></div>
          {(server?.canPickLocalFolder || server?.canManageCloud) && <div className="library-actions">
            {server?.canManageCloud && <button className="cloud-button" onClick={openCloudManager}><span aria-hidden="true">☁</span>连接云盘{server.cloudSourceCount > 0 ? ` · ${server.cloudSourceCount}` : ''}</button>}
            {server?.canPickLocalFolder && <button className="add-button" onClick={() => { setFolderError(''); setFolderOpen(true); }}><span className="folder-icon" aria-hidden="true" />添加媒体文件夹</button>}
          </div>}
        </div>

        {featured ? (
          <article className="feature-card">
            <div className="feature-art real-poster" aria-hidden="true">
              {featured.posterUrl && <img src={featured.posterUrl} alt="" />}
              <div className="feature-shade" />
            </div>
            <div className="feature-copy">
              <div className="format-row"><span>{featured.projection === 'flat' ? featured.kind.toUpperCase() : featured.projection.replace('equirect', 'VR')}</span><span>{featured.videoCodec?.toUpperCase() || featured.audioCodec?.toUpperCase()}</span><span>{featured.stereo.toUpperCase()}</span></div>
              <h2>{featured.title}</h2><p>{mediaLabel(featured)}</p>
              <div className="progress"><i style={{ width: `${featuredPercent}%` }} /></div>
              <div className="feature-actions">
                <button className="primary-button" onClick={() => { window.location.href = `/watch/${featured.id}`; }}>▶ {featuredProgress ? '继续播放' : '开始播放'} <small>{featuredProgress ? formatDuration(featuredProgress.position) : formatDuration(featured.duration)}</small></button>
                <button className="circle-button" aria-label="刷新媒体信息" onClick={() => void refreshLibrary()}>↻</button>
              </div>
            </div>
          </article>
        ) : !loading && (
          <div className="empty-state"><span>＋</span><h2>添加第一个媒体文件夹</h2><p>电脑上的文件不会离开当前局域网。</p>{server?.canPickLocalFolder && <button className="add-button" onClick={() => { setFolderError(''); setFolderOpen(true); }}>选择文件夹</button>}</div>
        )}

        <div className="section-title" id="recent"><div><h2>{filter === 'all' ? '最近添加' : filter === 'video' ? '视频' : filter === 'audio' ? '音频' : '最近播放'}</h2><span>{filtered.length} 个项目</span></div><button onClick={() => setFilter('all')}>查看全部 →</button></div>
        {loading ? <div className="loading-grid" aria-label="正在加载媒体库">{[0, 1, 2, 3].map((item) => <i key={item} />)}</div> : (
          <div className="media-grid">
            {filtered.map((item, index) => {
              const itemProgress = progress[item.id];
              const percent = itemProgress?.duration ? Math.min(100, itemProgress.position / itemProgress.duration * 100) : 0;
              return (
                <article className="media-card" key={item.id}>
                  <button className={`poster ${posterTones[index % posterTones.length]} ${item.kind === 'audio' ? 'audio-poster' : ''}`} aria-label={`播放 ${item.title}`} onClick={() => { window.location.href = `/watch/${item.id}`; }}>
                    {item.posterUrl && <img loading="lazy" src={item.posterUrl} alt="" />}
                    <span className="poster-index">{item.projection === 'equirect180' ? '180°' : item.projection === 'equirect360' ? '360°' : item.kind === 'audio' ? 'AUDIO' : String(index + 1).padStart(2, '0')}</span>
                    <span className="play-disc">▶</span>
                    {percent > 0 && <span className="card-progress"><i style={{ width: `${percent}%` }} /></span>}
                  </button>
                  <h3>{item.title}</h3><p>{mediaLabel(item)}</p>
                  {item.sourceType !== 'local' && <span className="cloud-source-badge">☁ {item.sourceType === 'baidu' ? '百度网盘' : '夸克 / WebDAV'}</span>}
                </article>
              );
            })}
          </div>
        )}
      </section>

      {folderOpen && (
        <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setFolderOpen(false); }}>
          <form className="folder-modal" onSubmit={addFolder}>
            <p className="eyebrow">COMPUTER LIBRARY</p><h2>添加媒体文件夹</h2><p>从电脑中选择文件夹，Localis 会递归扫描其中的视频与音频。</p>
            {server?.nativeFolderPicker && <button className="native-folder-button" type="button" disabled={folderBusy} onClick={() => void pickFolder()}><span className="folder-icon large" aria-hidden="true" /><span><strong>{folderBusy ? '等待文件夹选择…' : '打开本地文件夹'}</strong><small>使用 Windows 原生选择窗口</small></span><i aria-hidden="true">›</i></button>}
            <details className="manual-folder-entry"><summary>手动输入完整路径</summary><input autoFocus={!server?.nativeFolderPicker} aria-label="媒体文件夹路径" placeholder="D:\Videos" value={folderPath} onChange={(event) => setFolderPath(event.target.value)} /></details>
            {folderError && <div className="inline-error folder-error" role="alert">{folderError}</div>}
            <div><button type="button" onClick={() => setFolderOpen(false)}>取消</button><button className="add-button" type="submit" disabled={!folderPath.trim() || folderBusy}>添加并扫描</button></div>
          </form>
        </div>
      )}

      {cloudOpen && (
        <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setCloudOpen(false); }}>
          <section className="folder-modal cloud-modal" role="dialog" aria-modal="true" aria-labelledby="cloud-dialog-title">
            <p className="eyebrow">COMPUTER CLOUD BRIDGE</p><h2 id="cloud-dialog-title">连接云盘</h2>
            <p>云盘文件先经过这台电脑，超分与转码也全部在电脑端完成。Vision Pro 不会接触网盘凭据或下载地址。</p>

            {cloudSources.length > 0 && <div className="cloud-toolbar"><span>已连接 {cloudSources.length} 个云盘</span><button disabled={cloudBusy} onClick={() => void refreshCloudSources()}>↻ 重新扫描</button></div>}

            {cloudSources.length > 0 && <div className="cloud-source-list">
              {cloudSources.map((source) => <article key={source.id}>
                <div><strong>{source.name}</strong><small>{source.connection} · {source.fileCount} 个媒体文件 · {source.rootPath}</small>{source.error && <em>{source.error}</em>}</div>
                <button disabled={cloudBusy} onClick={() => void removeCloudSource(source.id)}>移除</button>
              </article>)}
            </div>}

            <div className="cloud-provider-tabs" role="tablist" aria-label="云盘类型">
              <button className={cloudProvider === 'quark' ? 'active' : ''} onClick={() => { setCloudProvider('quark'); setWebDav((current) => ({ ...current, rootPath: '/Quark' })); }}>夸克网盘</button>
              <button className={cloudProvider === 'baidu' ? 'active' : ''} onClick={() => { setCloudProvider('baidu'); setWebDav((current) => ({ ...current, rootPath: '/Baidu' })); }}>百度网盘</button>
            </div>

            {cloudProvider === 'baidu' ? (
              <form className="cloud-form" onSubmit={startBaiduAuthorization}>
                <div className="cloud-login-hero">
                  <span className="cloud-provider-mark baidu" aria-hidden="true">度</span>
                  <div><strong>扫码登录百度网盘</strong><span>无需在网页中填写 AppKey、SecretKey、地址或密码。授权完成后，媒体会自动出现在资料库。</span></div>
                </div>
                <div className={`cloud-notice ${cloudConnectors?.baidu.available ? 'ready' : 'warning'}`}>
                  <strong>{cloudConnectors?.baidu.available ? '官方设备码已就绪' : '等待 Localis 发布者配置官方应用'}</strong>
                  <span>{cloudConnectors?.baidu.available
                    ? `扫码后只读取“我的应用数据/${cloudConnectors.baidu.appFolder}”中的媒体；网盘文件仍由这台电脑读取。`
                    : cloudConnectors?.baidu.unavailableReason || '正在检查百度网盘登录能力…'}</span>
                </div>
                {baiduAuthorization && <div className="baidu-authorization"><img src={baiduAuthorization.qrCodeDataUrl} alt="百度网盘授权二维码" /><div><strong>使用百度网盘 App 扫码授权</strong><span>用户码：{baiduAuthorization.userCode || '见授权页面'}</span><a href={baiduAuthorization.verificationUrl} target="_blank" rel="noreferrer">打开百度授权页面</a><small>Localis 正在等待授权结果，短暂断网会自动重试。</small><button type="button" onClick={() => void cancelBaiduLink()}>取消本次授权</button></div></div>}
                {cloudError && <div className="inline-error folder-error" role="alert">{cloudError}</div>}
                {!cloudConnectors?.baidu.available && <details className="cloud-advanced"><summary>为什么这里没有配置输入框？</summary><p>百度官方授权仍要求应用身份。Localis 只允许发布者在电脑端安全配置一次，绝不让普通用户在 Vision Pro 页面传输 SecretKey；公共版本还需要通过百度开放平台审核。</p></details>}
                <div><button type="button" onClick={() => setCloudOpen(false)}>关闭</button><button className="add-button" disabled={cloudBusy || Boolean(baiduAuthorization) || !cloudConnectors?.baidu.available}>{baiduAuthorization ? '等待扫码…' : cloudBusy ? '正在连接…' : '显示登录二维码'}</button></div>
              </form>
            ) : (
              <div className="cloud-form">
                <div className="cloud-login-hero">
                  <span className="cloud-provider-mark quark" aria-hidden="true">夸</span>
                  <div><strong>扫码登录夸克网盘</strong><span>目标体验已经预留，但当前没有安全、公开且支持目录与 Range 播放的官方接口。</span></div>
                </div>
                <div className="cloud-notice warning"><strong>暂不启用不安全的“假直连”</strong><span>{cloudConnectors?.quark.unavailableReason || '正在检查夸克网盘登录能力…'}</span></div>
                <button className="cloud-unavailable-button" type="button" disabled>等待夸克官方开放直连接口</button>
                <details className="cloud-advanced">
                  <summary>高级兼容：我已有本机 OpenList</summary>
                  <form className="cloud-form advanced-webdav-form" onSubmit={connectWebDav}>
                    <div className="cloud-notice"><strong>仅连接你已经信任的本机只读桥接</strong><span>OpenList 必须只监听 127.0.0.1，并使用单独的 WebDAV Read 账号和 Native Proxy。Localis 不抓取夸克 Cookie，也不会自动安装会把登录票据交给第三方的驱动。</span></div>
                    <label>OpenList WebDAV 地址<input required aria-label="OpenList WebDAV 地址" value={webDav.baseUrl} onChange={(event) => setWebDav({ ...webDav, baseUrl: event.target.value })} placeholder="http://127.0.0.1:5244/dav/" /></label>
                    <label>云盘挂载路径<input required aria-label="云盘挂载路径" value={webDav.rootPath} onChange={(event) => setWebDav({ ...webDav, rootPath: event.target.value })} placeholder="/Quark" /></label>
                    <label>只读用户名<input required aria-label="OpenList 只读用户名" value={webDav.username} onChange={(event) => setWebDav({ ...webDav, username: event.target.value })} autoComplete="username" /></label>
                    <label>只读密码<input required aria-label="OpenList 只读密码" type="password" value={webDav.password} onChange={(event) => setWebDav({ ...webDav, password: event.target.value })} autoComplete="current-password" /></label>
                    <button className="add-button" disabled={cloudBusy}>{cloudBusy ? '正在测试并扫描…' : '连接现有桥接'}</button>
                  </form>
                </details>
                {cloudError && <div className="inline-error folder-error" role="alert">{cloudError}</div>}
                <div><button type="button" onClick={() => setCloudOpen(false)}>关闭</button></div>
              </div>
            )}
          </section>
        </div>
      )}
    </main>
  );
}
