'use client';
/* eslint-disable @next/next/no-img-element -- Posters are authenticated, same-origin files generated by this LAN server. */
/* eslint-disable @next/next/no-location-assign-relative-destination -- Vinext's Next navigation shims currently duplicate React context in this client runtime. */

import { FormEvent, useEffect, useMemo, useState } from 'react';
import type { PlaybackProgress, PublicMediaItem } from '@/server/types';

interface LibraryResponse {
  items: PublicMediaItem[];
  progress: Record<string, PlaybackProgress>;
}

interface ServerInfo {
  secure: boolean;
  encoder: string;
  mediaCount: number;
  libraryCount: number;
  lanUrls: string[];
  publicUrl?: string;
  canPickLocalFolder: boolean;
  nativeFolderPicker: boolean;
}

const posterTones = ['violet', 'ocean', 'ember', 'mint', 'gold', 'rose'];
const pairingMessages: Record<string, string> = {
  invalid_pairing_code: '配对码不正确，请查看电脑端本次启动显示的六位数字。',
  too_many_attempts: '尝试次数过多，请等待五分钟后再试。',
  origin_required: '浏览器安全校验失败，请从 Localis 页面重新配对。',
};

function formatDuration(seconds: number) {
  if (!Number.isFinite(seconds) || seconds <= 0) return '—';
  const total = Math.floor(seconds);
  const hours = Math.floor(total / 3600);
  const minutes = Math.floor((total % 3600) / 60);
  const remainder = total % 60;
  return hours > 0
    ? `${hours}:${String(minutes).padStart(2, '0')}:${String(remainder).padStart(2, '0')}`
    : `${minutes}:${String(remainder).padStart(2, '0')}`;
}

function mediaLabel(item: PublicMediaItem) {
  const resolution = item.width && item.height ? `${item.width}×${item.height}` : item.kind === 'audio' ? '音频' : '视频';
  if (item.projection === 'equirect180') return `VR180 · ${item.stereo.toUpperCase()} · ${resolution}`;
  if (item.projection === 'equirect360') return `360° · ${item.stereo.toUpperCase()} · ${resolution}`;
  return `${resolution} · ${(item.videoCodec || item.audioCodec || item.extension.slice(1)).toUpperCase()}`;
}

async function jsonFetch<T>(url: string, init?: RequestInit): Promise<T> {
  const response = await fetch(url, {
    credentials: 'include',
    ...init,
    headers: { 'Content-Type': 'application/json', ...init?.headers },
  });
  const body = await response.json().catch(() => ({})) as Record<string, unknown>;
  if (!response.ok) throw Object.assign(new Error(String(body.message || body.error || `HTTP ${response.status}`)), { status: response.status });
  return body as T;
}

export function MediaLibraryView() {
  const [items, setItems] = useState<PublicMediaItem[]>([]);
  const [progress, setProgress] = useState<Record<string, PlaybackProgress>>({});
  const [server, setServer] = useState<ServerInfo>();
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState<'all' | 'recent' | 'video' | 'audio'>('all');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [needsPairing, setNeedsPairing] = useState(false);
  const [pairCode, setPairCode] = useState('');
  const [pairError, setPairError] = useState('');
  const [folderOpen, setFolderOpen] = useState(false);
  const [folderPath, setFolderPath] = useState('');
  const [folderBusy, setFolderBusy] = useState(false);
  const [folderError, setFolderError] = useState('');

  const loadLibrary = async () => {
    setLoading(true);
    setError('');
    try {
      const status = await jsonFetch<{ paired: boolean }>('/api/pair/status');
      if (!status.paired) {
        setNeedsPairing(true);
        return;
      }
      const [library, serverInfo] = await Promise.all([
        jsonFetch<LibraryResponse>('/api/library'),
        jsonFetch<ServerInfo>('/api/server'),
      ]);
      setItems(library.items);
      setProgress(library.progress);
      setServer(serverInfo);
      setNeedsPairing(false);
    } catch (cause) {
      const status = (cause as { status?: number }).status;
      if (status === 401) setNeedsPairing(true);
      else setError(cause instanceof Error ? cause.message : '无法连接 Localis 服务');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    const timer = window.setTimeout(() => void loadLibrary(), 0);
    return () => window.clearTimeout(timer);
  }, []);
  useEffect(() => {
    const shortcut = (event: KeyboardEvent) => {
      if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') {
        event.preventDefault();
        document.querySelector<HTMLInputElement>('#media-search')?.focus();
      }
    };
    window.addEventListener('keydown', shortcut);
    return () => window.removeEventListener('keydown', shortcut);
  }, []);

  const filtered = useMemo(() => items.filter((item) => {
    if (filter === 'video' && item.kind !== 'video') return false;
    if (filter === 'audio' && item.kind !== 'audio') return false;
    if (filter === 'recent' && !progress[item.id]?.position) return false;
    return `${item.title} ${item.fileName} ${item.relativePath}`.toLowerCase().includes(query.trim().toLowerCase());
  }), [items, progress, query, filter]);
  const featured = items.find((item) => item.kind === 'video' && progress[item.id]?.position > 0)
    || items.find((item) => item.kind === 'video')
    || items[0];
  const featuredProgress = featured ? progress[featured.id] : undefined;
  const featuredPercent = featuredProgress?.duration
    ? Math.min(100, (featuredProgress.position / featuredProgress.duration) * 100)
    : 0;

  const pair = async (event: FormEvent) => {
    event.preventDefault();
    setPairError('');
    try {
      await jsonFetch('/api/pair/verify', { method: 'POST', body: JSON.stringify({ code: pairCode }) });
      setPairCode('');
      await loadLibrary();
    } catch (cause) {
      const message = cause instanceof Error ? cause.message : '';
      setPairError(pairingMessages[message] || message || '配对失败');
    }
  };

  const addFolder = async (event: FormEvent) => {
    event.preventDefault();
    if (!folderPath.trim()) return;
    try {
      await jsonFetch('/api/library/folders', { method: 'POST', body: JSON.stringify({ path: folderPath }) });
      setFolderPath('');
      setFolderOpen(false);
      await loadLibrary();
    } catch (cause) {
      setFolderError(cause instanceof Error ? cause.message : '添加文件夹失败');
    }
  };

  const pickFolder = async () => {
    setFolderBusy(true);
    setFolderError('');
    try {
      const result = await jsonFetch<{ cancelled: boolean; selected?: string }>('/api/library/folders/pick', { method: 'POST', body: '{}' });
      if (!result.cancelled) {
        setFolderPath('');
        setFolderOpen(false);
        await loadLibrary();
      }
    } catch (cause) {
      setFolderError(cause instanceof Error ? cause.message : '无法打开文件夹选择器');
    } finally {
      setFolderBusy(false);
    }
  };

  if (needsPairing) {
    return (
      <main className="pairing-page">
        <section className="pairing-panel">
          <span className="brand-mark large"><i /></span>
          <p className="eyebrow">PRIVATE LAN CONNECTION</p>
          <h1>连接你的私人媒体库</h1>
          <p>在电脑端 Localis 窗口中找到六位配对码。视频始终通过当前局域网传输。</p>
          <form onSubmit={pair}>
            <input aria-label="六位配对码" autoFocus autoComplete="one-time-code" inputMode="numeric" maxLength={6} pattern="[0-9]{6}" placeholder="000000" value={pairCode} onChange={(event) => setPairCode(event.target.value.replace(/\D/g, ''))} />
            <button disabled={pairCode.length !== 6}>安全连接</button>
          </form>
          {pairError && <div className="inline-error" role="alert">{pairError}</div>}
          <small>Vision Pro 端无需安装 App、证书或描述文件</small>
        </section>
      </main>
    );
  }

  return (
    <main className="app-shell">
      <aside className="sidebar">
        <a className="brand" href="#" aria-label="Localis 首页"><span className="brand-mark"><i /></span><span>Localis</span></a>
        <nav aria-label="媒体导航">
          <button className={`nav-item ${filter === 'all' ? 'active' : ''}`} onClick={() => setFilter('all')}><span>⌂</span>媒体库</button>
          <button className={`nav-item ${filter === 'recent' ? 'active' : ''}`} onClick={() => setFilter('recent')}><span>◷</span>最近播放</button>
          <button className={`nav-item ${filter === 'video' ? 'active' : ''}`} onClick={() => setFilter('video')}><span>▣</span>视频</button>
          <button className={`nav-item ${filter === 'audio' ? 'active' : ''}`} onClick={() => setFilter('audio')}><span>♫</span>音频</button>
        </nav>
        <div className="sidebar-spacer" />
        <div className="server-card">
          <div className="server-line"><span className="status-dot" />局域网服务在线</div>
          <strong>{server?.publicUrl || server?.lanUrls[0]?.replace(/^https?:\/\//, '') || '正在检测…'}</strong>
          <small>{server?.secure ? '可信 HTTPS · WebXR 可用' : 'HTTP · 仅桌面测试 WebXR'}</small>
        </div>
        <button className="nav-item" onClick={() => void loadLibrary()}><span>↻</span>刷新媒体库</button>
      </aside>

      <section className="content" id="library">
        <header className="topbar">
          <label className="search"><span>⌕</span><input id="media-search" aria-label="搜索媒体" placeholder="搜索影片、音乐或文件夹" value={query} onChange={(event) => setQuery(event.target.value)} /><kbd>⌘ K</kbd></label>
          <button className="pair-button"><span className="status-dot" />当前设备已配对</button>
          <button className="avatar" aria-label="Localis 服务状态">L</button>
        </header>

        {!server?.secure && typeof window !== 'undefined' && !['localhost', '127.0.0.1'].includes(window.location.hostname) && (
          <div className="security-banner"><strong>普通播放可用</strong><span>当前地址不是可信 HTTPS，浏览器会禁用 WebXR。请使用 Localis 提供的可信域名。</span></div>
        )}
        {error && <div className="inline-error library-error" role="alert">{error}<button onClick={() => setError('')}>关闭</button></div>}

        <div className="page-heading">
          <div><p className="eyebrow">YOUR PRIVATE CINEMA</p><h1>晚上好，继续探索。</h1></div>
          {server?.canPickLocalFolder && <button className="add-button" onClick={() => { setFolderError(''); setFolderOpen(true); }}><span className="folder-icon" aria-hidden="true" />添加媒体文件夹</button>}
        </div>

        {featured ? (
          <article className="feature-card">
            <div className="feature-art real-poster" aria-hidden="true">
              {featured.posterUrl && <img src={featured.posterUrl} alt="" />}
              <div className="feature-shade" />
            </div>
            <div className="feature-copy">
              <div className="format-row"><span>{featured.projection === 'flat' ? featured.kind.toUpperCase() : featured.projection.replace('equirect', 'VR')}</span><span>{featured.videoCodec?.toUpperCase() || featured.audioCodec?.toUpperCase()}</span><span>{featured.stereo.toUpperCase()}</span></div>
              <h2>{featured.title}</h2><p>{mediaLabel(featured)}</p>
              <div className="progress"><i style={{ width: `${featuredPercent}%` }} /></div>
              <div className="feature-actions">
                <button className="primary-button" onClick={() => { window.location.href = `/watch/${featured.id}`; }}>▶ {featuredProgress ? '继续播放' : '开始播放'} <small>{featuredProgress ? formatDuration(featuredProgress.position) : formatDuration(featured.duration)}</small></button>
                <button className="circle-button" aria-label="刷新媒体信息" onClick={() => void loadLibrary()}>↻</button>
              </div>
            </div>
          </article>
        ) : !loading && (
          <div className="empty-state"><span>＋</span><h2>添加第一个媒体文件夹</h2><p>电脑上的文件不会离开当前局域网。</p>{server?.canPickLocalFolder && <button className="add-button" onClick={() => { setFolderError(''); setFolderOpen(true); }}>选择文件夹</button>}</div>
        )}

        <div className="section-title" id="recent"><div><h2>{filter === 'all' ? '最近添加' : filter === 'video' ? '视频' : filter === 'audio' ? '音频' : '最近播放'}</h2><span>{filtered.length} 个项目</span></div><button onClick={() => setFilter('all')}>查看全部 →</button></div>
        {loading ? <div className="loading-grid" aria-label="正在加载媒体库">{[0, 1, 2, 3].map((item) => <i key={item} />)}</div> : (
          <div className="media-grid">
            {filtered.map((item, index) => {
              const itemProgress = progress[item.id];
              const percent = itemProgress?.duration ? Math.min(100, itemProgress.position / itemProgress.duration * 100) : 0;
              return (
                <article className="media-card" key={item.id}>
                  <button className={`poster ${posterTones[index % posterTones.length]} ${item.kind === 'audio' ? 'audio-poster' : ''}`} aria-label={`播放 ${item.title}`} onClick={() => { window.location.href = `/watch/${item.id}`; }}>
                    {item.posterUrl && <img loading="lazy" src={item.posterUrl} alt="" />}
                    <span className="poster-index">{item.projection === 'equirect180' ? '180°' : item.projection === 'equirect360' ? '360°' : item.kind === 'audio' ? 'AUDIO' : String(index + 1).padStart(2, '0')}</span>
                    <span className="play-disc">▶</span>
                    {percent > 0 && <span className="card-progress"><i style={{ width: `${percent}%` }} /></span>}
                  </button>
                  <h3>{item.title}</h3><p>{mediaLabel(item)}</p>
                </article>
              );
            })}
          </div>
        )}
      </section>

      {folderOpen && (
        <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setFolderOpen(false); }}>
          <form className="folder-modal" onSubmit={addFolder}>
            <p className="eyebrow">COMPUTER LIBRARY</p><h2>添加媒体文件夹</h2><p>从电脑中选择文件夹，Localis 会递归扫描其中的视频与音频。</p>
            {server?.nativeFolderPicker && <button className="native-folder-button" type="button" disabled={folderBusy} onClick={() => void pickFolder()}><span className="folder-icon large" aria-hidden="true" /><span><strong>{folderBusy ? '等待文件夹选择…' : '打开本地文件夹'}</strong><small>使用 Windows 原生选择窗口</small></span><i aria-hidden="true">›</i></button>}
            <details className="manual-folder-entry"><summary>手动输入完整路径</summary><input autoFocus={!server?.nativeFolderPicker} aria-label="媒体文件夹路径" placeholder="D:\Videos" value={folderPath} onChange={(event) => setFolderPath(event.target.value)} /></details>
            {folderError && <div className="inline-error folder-error" role="alert">{folderError}</div>}
            <div><button type="button" onClick={() => setFolderOpen(false)}>取消</button><button className="add-button" type="submit" disabled={!folderPath.trim() || folderBusy}>添加并扫描</button></div>
          </form>
        </div>
      )}
    </main>
  );
}
